#!/usr/bin/python
import os, sys

if len(sys.argv) != 3:
	print "Usage: build-from-release project-name version"
	sys.exit(1)

project = sys.argv[1]
version = sys.argv[2]

packaging = "debian-packages/%s" % project
if os.path.exists ("packages/%s" % project):
	packaging = "packages/%s" % project

release = "releases/%s-%s.tar.xz" % (project, version)
orig = "build/%s_%s.orig.tar.xz" % (project, version)
build_project = "build/"
if not os.path.exists (release):
	print "ERROR: %s not found!" % release
	sys.exit(1)

os.system("mkdir -p build")
os.system("rm -rf build/%s*" % project)
os.system("tar xvfJ %s -C build/" % release) # Uncompress the release
os.system("mv build/%s* build/%s" % (project, project))
os.system("cp %s %s" % (release, orig)) # Add the orig
os.system("cp -R %s/* build/%s/" % (packaging, project)) # Add the debian dir
os.system("cp -R %s/.pc build/%s/" % (packaging, project)) # Add the .pc dir
